### ISSUE TITLE
Use Typhoeus instead plain Net::HTTP

### ISSUE THREAD

**Issue by mikhailov** [twilio/twilio-ruby#185]
Guys, would you consider to switch to advanced HTTP client like Typhoeus or similar? Advantages are simple: use keepalive, nice DSL to handle timeouts, retries, concurrent requests.

**Comment by carlosdp** [comment]
We're releasing a version of the library soon that will allow for pluggable HTTP clients.

**Comment by mikhailov** [comment]
👍

**Comment by viktornonov** [comment]
@mikhailov I'm using typhoeus through this monkey patch until the new version of the gem is released:

https://gist.github.com/viktornonov/487e0d56ea6ad8873f54

Hopefully it will help you.

**Comment by mikhailov** [comment]
@viktornonov is that correct to say, your patches overwrites *post* method from https://github.com/twilio/twilio-ruby/blob/c4ffe31cbd73f15a961d70d134a09adc3cee88b8/lib/twilio-ruby/rest/base_client.rb#L44-L56 ? What exactly provides an improvements apart from Accept-Encoding (https://gist.github.com/viktornonov/487e0d56ea6ad8873f54#file-twilio-parallel-rb-L17)?

**Comment by viktornonov** [comment]
@mikhailov Yes, it overrides the Post method of the https://github.com/twilio/twilio-ruby/blob/c4ffe31cbd73f15a961d70d134a09adc3cee88b8/lib/twilio-ruby/rest/base_client.rb#L44-L56 .

I had the problem with a segfault when I send multiple sms messages through a sidekiq worker and this override fixes it. The issue is related to Ruby's Net::HTTP module and openssl and to that Net::HTTP is not thread safe. You can see more details about the problem in #93.

It will be interesting to check the performance change, I can check this and post the results here. What do you think is the best thing that I can use to measure the performance - the Ruby's Benchmark module?

**Comment by mikhailov** [comment]
@viktornonov for performance testing only one rule - it shouldn't be Apache Bench, a good option is siege or alternatives. Rube benchmark module can be good as well!

**Comment by carlosdp** [comment]
If you upgrade to the `5.0.0.rc2` release candidate, it ships with Faraday by default and a bunch of other features. You can use Typhoeus easily using: `@client.http_client.adapter = :typhoeus`. [See the upgrade wiki](https://github.com/twilio/twilio-ruby/wiki/Ruby-Version-5.x-Upgrade-Guide) for more details!

**Comment by mikhailov** [comment]
@carlosdp 👍
