### ISSUE TITLE
Rails: private method 'configuration' called for Twilio:Module when SID/TOKEN missing

### ISSUE THREAD

**Issue by januszm** [twilio/twilio-ruby#227]
UPDATE: It breaks with this error message when SID and TOKEN are not present. Might be related to this commit? https://github.com/twilio/twilio-ruby/commit/c36bfcd96313735a751fe5e60d964c96003740ee
There's a call to ```Twilio.configuration``` method which seems to be private https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby.rb#L56

**5.0.0.rc14:**
**account.messages.create**

### Code Snippet
```ruby
def send_sms(content)
    begin
      @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
      message = @client.account.messages.create(
        from: ENV['TWILIO_PHONE_NUMBER'], ...
```

### Exception / Log
```
  private method `configuration' called for Twilio:Module
  app/services/some_service.rb:XX:in `new'
```

### Steps to Reproduce
1. Run Rails app in production mode
2. Try instantiating new REST Client with SID and TOKEN

**Comment by philnash** [comment]
I was thinking that that would be weird to only break in production mode, and you've definitely uncovered a bug. I would check your environment variables that you have set in your production mode though @januszm. If `ENV["TWILIO_ACCOUNT_SID"]` was a value, [this line in the `Twilio::REST::Client`](https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby/rest/client.rb#L17)  would short circuit and you'd never call the private method.

So, that's where I think the issue is in our code too. There shouldn't be a call to `configuration` at all. There are [class level delegators to `account_sid` and `auth_token`](https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby.rb#L42) available that we should be using, as [we do in the current v4 version](https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/rest/base_client.rb#L29-L30). @ihumanable, could you take a look as this is in a generated file?

Cheers!

**Comment by januszm** [comment]
I'm sorry for this report @philnash this is obviously my mistake - I forgot to set the ENV variables for the production environment (in fact, different server where they're not set at all). I'll close this issue.

However, there is some value in this report - looks like the error message should sound slightly different, probably 'missing SID / TOKEN' or something along those lines.

Thanks!

**Comment by philnash** [comment]
It's definitely still an issue on our side too. If you were expecting to set the Twilio config site wide using the following pattern:

```ruby
Twilio.configure do |config|
  config.account_sid = ENV["TWILIO_ACCOUNT_SID"]
  config.auth_token = ENV["TWILIO_AUTH_TOKEN"]
end
```

and then initialize the client like:

```ruby
client = Twilio::REST::Client.new
```

then this would blow up with the same error. I'm reopening as [these lines](https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby/rest/client.rb#L17-L18) should call straight to the `account_sid` and `auth_token` delegators, not through the private `configuration` method.

**Comment by philnash** [comment]
Glad your issue is sorted  though @januszm!

**Comment by philnash** [comment]
This has been fixed as you can see here: https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby/rest/client.rb#L17-L18
