### ISSUE TITLE
[DEPRECATED] SMS Resource is deprecated. Please use Messages (https://www.twilio.com/docs/api/rest/message)

### ISSUE THREAD

**Issue by sahilchopra** [twilio/twilio-ruby#228]

**Comment by philnash** [comment]
Hi @sahilchopra.

I guess you're reporting this because you received this message when doing a call like:

```ruby
client = Twilio::REST::Client.new ENV["ACCOUNT_SID"], ENV["AUTH_TOKEN"]
client.account.messages.sms.create(:to => TO_NUMBER, :from => YOUR_TWILIO_NUMBER, :body => "Hello!")
```

To get rid of the deprecated message, all you need to do is lose the call to `sms` in the middle there. Just do:

```ruby
client = Twilio::REST::Client.new ENV["ACCOUNT_SID"], ENV["AUTH_TOKEN"]
client.account.messages.create(:to => TO_NUMBER, :from => YOUR_TWILIO_NUMBER, :body => "Hello!")
```

This will then use the [Messages](https://www.twilio.com/docs/api/rest/message) endpoint instead of the deprecated SMS/Messages endpoint and your application will be much happier.

**Comment by sahilchopra** [comment]
thanks @philnash

**Comment by philnash** [comment]
No problems! Give me a shout if you have any other questions.
