### ISSUE TITLE
How to send a test SMS?

### ISSUE THREAD

**Issue by 9mm** [twilio/twilio-ruby#231]
When I send a SMS via test credentials I don't get any texts. I try to inspect the object after I create the message to see if maybe theres `sent_at` set or anything, and I don't see it.

How do I actually SEND the test text? Thanks

**Comment by jingming** [comment]
Please direct this question to help@twilio.com

**Comment by philnash** [comment]
Hey @9mm,

[Test credentials](https://www.twilio.com/docs/api/rest/test-credentials) are just there to make sure you are sending the right data to Twilio to send a message. They don't actually send messages.

In order to send a message you will need to use your real Account SID and Auth Token. If you haven't yet upgraded your account, you will be able to [send messages to numbers that you have verified](https://support.twilio.com/hc/en-us/articles/223136107-How-does-Twilio-s-Free-Trial-work-). Messages sent whilst you are still in trial account mode don't cost you anything. Once you have upgraded your account you can send SMS messages to any number you want to.
