### ISSUE TITLE
Feature Request - Use the Twilio client to sign requests and download the TwiML bin URLs

### ISSUE THREAD

**Issue by ndbroadbent** [twilio/twilio-ruby#268]
I'm writing a script to manage data in a Twilio account, and I need to download the TwiML data from the bin URLs. I couldn't find an obvious way to sign the requests, so it would be great if I could do this with `twilio-ruby`.

It would be great if there could be a Ruby example for the JS script mentioned here: https://support.twilio.com/hc/en-us/articles/223132187--Not-Authorized-error-when-trying-to-view-TwiML-Bin-URL

**Comment by ndbroadbent** [comment]
If anyone else reads this, here's a working solution in Ruby, using the [HTTParty gem](https://github.com/jnunemaker/httparty):

```ruby
validator = Twilio::Util::RequestValidator.new(account.auth_token)
url = "#{number.voice_url}?AccountSid=#{account.sid}"
twilio_sig = validator.build_signature_for(url, [])
response = HTTParty.get(url, headers: { 'X-TWILIO-SIGNATURE': twilio_sig })

#  => #<HTTParty::Response:0x7f8d1ca12178 parsed_response={"Response"=>{"Dial"=>"555-555-5555"}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["text/xml"], "date"=>["Thu, 01 Jun 2017 20:28:49 GMT"], "server"=>["nginx"], "strict-transport-security"=>["max-age=15768000", "max-age=15768000"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-shenanigans"=>["none"], "x-xss-protection"=>["1; mode=block"], "content-length"=>["92"], "connection"=>["Close"]}>
```

**Comment by ndbroadbent** [comment]
P.S. It would be great if a Twilio staff member could add something like this to the docs: https://support.twilio.com/hc/en-us/articles/223132187--Not-Authorized-error-when-trying-to-view-TwiML-Bin-URL

**Comment by owenstrevor** [comment]
@ndbroadbent your method didn't work for me, after banging my head against the wall I found a simple solution with HTTParty:
```
    auth = {
      username: ACCOUNT_SID,
      password: AUTH_TOKEN
    }
    options = { basic_auth: auth }
    result = HTTParty.get(payload_url, options)
```

**Comment by owenstrevor** [comment]
This problem came back from the grave and the above solution I submitted no longer worked in my app. I was getting a 400 response with HTTParty and with Net::HTTP.get but visiting the payload URL in the browser and entering my username/password worked fine.

This was the 400 response:

`Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified`

After some head banging I realized the response was coming from AmazonS3 and not Twilio, so it was the redirect that was the problem. By breaking the GET request into two steps I was able to fix this.

```
response = HTTParty.get(authed_payload_url, follow_redirects: false)
HTTParty.get(response.headers['location'])
```

I added my credentials into the URL itself to create **authed_payload_url** like shown in [this article](https://www.twilio.com/docs/usage/your-request-to-twilio).

Hope this helps someone!
