### ISSUE TITLE
 TwiML generator: Play verb requires named parameter for url

### ISSUE THREAD

**Issue by mlund01** [twilio/twilio-ruby#317]
I ran into an error today when trying to play a message. This was my ruby code to generate TwiML,

```ruby
response = Twilio::TwiML::VoiceResponse.new do |r|
          r.play @phone_notification.recording_url
          r.hangup
        end.to_s
```

which caused this error to come up,
`ArgumentError: wrong number of arguments (given 1, expected 0)` for the `r.play` invocation. So after playing around I changed it to this,

```ruby
response = Twilio::TwiML::VoiceResponse.new do |r|
          r.play(url: @phone_notification.recording_url)
          r.hangup
        end.to_s
```

Which ended up working, with the key difference being I had to provide a named parameter for the url, where I didn't have to before. So my question is, was this an intended change? If so, it seems a bit inconsistent with some of the other verbs, such as Say or Sms, where the first parameter doesn't need to be named and can just be the string of what you want the content of the TwiML element to be, whereas all the named parameters end up being attributes. However, this same set of rules doesn't apply to the Play verb, where a named parameter is required for the url, which will then be set as the content of the TwiML element.

**Comment by efossier** [comment]
@mlund01 This was intentional and I believe the change was made because url is actually not required in the Play element and therefore we made the parameter optional. 

Unnamed and named parameters don't map to content of the element and attributes intentionally, although in practice this is often true we are actually trying to capture required parameters as unnamed, positional arguments and any additional optional parameter will be named.

This particular case appears to have been unintentionally backwards incompatible, sorry for the confusion and trouble caused!

**Comment by simaoneves** [comment]
Because of this, the Twilio quickstart docs are wrong, at least this one is:
https://www.twilio.com/docs/quickstart/ruby/twiml/connect-call-to-second-person

**Comment by philnash** [comment]
Thanks for reporting that @simaoneves, I've fixed the quickstart doc that you linked to.
