### ISSUE TITLE
ArgumentError: unknown keyword status_callback_method

### ISSUE THREAD

**Issue by antonhalim** [twilio/twilio-ruby#327]
**Version: 5.1.0**

### Code Snippet
```ruby
Twilio[:VERSION] # 5.1.0

client = Twilio::REST::Client.new(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)
client.api.account.messages.create(
			from: twilio_number,
			to: recipient_number,
			body: 'message body',
			status_callback_method: 'POST',
			status_callback: callback_url
		)
```

### Exception/Log
```
ArgumentError: unknown keyword: status_callback_method
```

### Steps to Reproduce
1. Set up Twilio::REST::CLient
2. Trying to send an SMS with status_callback url and status_callback_method specified
3. Error given

### Expected behavior
It should send the SMS and post to the given callback URL

**Comment by DavidIValencia** [comment]
@antonhalim hey there.  StatusCallbackMethod is actually not a part of the REST api for messages, which I guess is a bit confusing because it is a part of the api for calls.  The default of the StatusCallback seems to be POST already, so you can go ahead and just remove that line from your call and you should reach your intended behavior.

Here's the description from the docs for the messages StatusCallback: 

"A URL where Twilio will POST each time your message status changes to one of the following: queued, failed, sent, delivered, or undelivered. Twilio will POST the MessageSid along with the other standard request parameters as well as MessageStatus and ErrorCode. If this parameter passed in addition to a MessagingServiceSid, Twilio will override the Status Callback URL of the Messaging Service. Non-relative URLs must contain a valid hostname (underscores are not allowed)."

https://www.twilio.com/docs/api/rest/sending-messages

And now here is the one for StatusCallback for calls:

"A URL that Twilio will send asynchronous webhook requests to on every call event specified in the StatusCallbackEvent parameter. If no event is present, Twilio will send completed by default. If an ApplicationSid parameter is present, this parameter is ignored. URLs must contain a valid hostname (underscores are not permitted)."

https://www.twilio.com/docs/api/rest/making-calls

Hope that works for you!

**Comment by antonhalim** [comment]
@DavidIValencia Thank you for the reply! I clearly confused by the docs.
